name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  WEBAPP_NAME: hamsterblog
  WEBAPP_PACKAGE_PATH: './published'
jobs:
  build:

    runs-on: win-runner

    steps:
    - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Release -o ${{ env.WEBAPP_PACKAGE_PATH }}
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
        SOURCE_DIR: ${{ env.WEBAPP_PACKAGE_PATH }}      # optional: defaults to entire repository
    
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ${{ format('{}/*', env.WEBAPP_PACKAGE_PATH) }} C:/inetpub/wwwroot/dotnetcore-webapp -Recurse -Force
        iisreset /start
    
    - name: Curl the website as a smoke test
      run: curl http://localhost/dotnetcore-webapp

    - name: Run Web Test
      run: |
        dotnet build --configuration Release .\dotnet-core-webapp.webtest
        cd .\dotnet-core-webapp.webtests
        dotnet test
